defaults:
  debug: false
  base_dir: "."
  http_proxy:
    use_proxy: false
    proxy_url: ""
    proxy_port: 8080
    proxy_user: ""
    proxy_pass: ""

ldap:
  base_dn: ""
  uri: ""
  user: ""
  pass: ""
  queries:
    all_users: ""
    user_is_valid: ""
    user_is_active: ""
    user_info: ""
  fields:
    full_name: ""
    first_name: ""
    role: ""
    team: ""
    org: ""
    location: ""
    start_date: ""
    uid_number: ""
    groups: ""
    photo_url: ""

pagerduty:
  base_url: "https://api.pagerduty.com/"
  api_key: ""

duo:
  host: ""
  ikey: ""
  skey: ""
  ca_certs: ""

google_apps:
  admin_user: "gatekeeper-admin"
  offboarded_ou: "/Offboarded Users"
  domain: ""
  credentials_keyfile: "config/google_api_service_account_keyfile.json"
  api_scopes:
    - "https://www.googleapis.com/auth/admin.directory.user"
    - "https://www.googleapis.com/auth/admin.directory.user.security"
    - "https://www.googleapis.com/auth/admin.directory.group.member"
    - "https://www.googleapis.com/auth/gmail.settings.basic"
    - "https://www.googleapis.com/auth/gmail.settings.sharing"
    - "https://www.googleapis.com/auth/calendar"
    - "https://www.googleapis.com/auth/drive"

# You normally donot need to modify the config beyond this point.
# Note: the items in the following lists MUST match the names of the fields for each form.
# See forms.py for more info.
actions:
  google_admin: &google_admin
    RESET_PASSWORD: true
    DELETE_ASPS: true
    DELETE_TOKENS: true
    INVALIDATE_BACKUP_CODES: true
    ORG_UNIT_CHANGE: true
    ORG_UNIT_RESET: true
  google_gmail: &google_gmail
    SET_OOO_MSG: true
    DISABLE_IMAP: true
    DISABLE_POP: true
  google_calendar: &google_calendar
    CHANGE_EVENTS_OWNERSHIP: true
    REMOVE_FUTURE_EVENTS: true
  google_drive: &google_drive
    NEW_FILES_OWNER: true
    FILE_SEARCH: true
  pagerduty: &pagerduty
    REMOVE_FROM_ONCALLS: true
  duo: &duo
    REMOVE_FROM_DUO: true

# This is where you can select the default options available for each action group.
action_groups:
  offboard:
    <<: *google_admin
    <<: *google_gmail
    <<: *google_calendar
    <<: *pagerduty
  lost_asset:
    - RESET_PASSWORD
    - DELETE_ASPS
    - DELETE_TOKENS
    - INVALIDATE_BACKUP_CODES
    - DISABLE_IMAP
    - DISABLE_POP
